// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: complexpb/complex.proto

package complexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComplexMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dummy *DummyMessage   `protobuf:"bytes,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	List  []*DummyMessage `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ComplexMessage) Reset() {
	*x = ComplexMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_complexpb_complex_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComplexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexMessage) ProtoMessage() {}

func (x *ComplexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_complexpb_complex_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexMessage.ProtoReflect.Descriptor instead.
func (*ComplexMessage) Descriptor() ([]byte, []int) {
	return file_complexpb_complex_proto_rawDescGZIP(), []int{0}
}

func (x *ComplexMessage) GetDummy() *DummyMessage {
	if x != nil {
		return x.Dummy
	}
	return nil
}

func (x *ComplexMessage) GetList() []*DummyMessage {
	if x != nil {
		return x.List
	}
	return nil
}

type DummyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DummyMessage) Reset() {
	*x = DummyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_complexpb_complex_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DummyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyMessage) ProtoMessage() {}

func (x *DummyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_complexpb_complex_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyMessage.ProtoReflect.Descriptor instead.
func (*DummyMessage) Descriptor() ([]byte, []int) {
	return file_complexpb_complex_proto_rawDescGZIP(), []int{1}
}

func (x *DummyMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DummyMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_complexpb_complex_proto protoreflect.FileDescriptor

var file_complexpb_complex_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x78, 0x22, 0x68, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x2e, 0x44, 0x75,
	0x6d, 0x6d, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x64, 0x75, 0x6d, 0x6d,
	0x79, 0x12, 0x29, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x2e, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x0c,
	0x44, 0x75, 0x6d, 0x6d, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_complexpb_complex_proto_rawDescOnce sync.Once
	file_complexpb_complex_proto_rawDescData = file_complexpb_complex_proto_rawDesc
)

func file_complexpb_complex_proto_rawDescGZIP() []byte {
	file_complexpb_complex_proto_rawDescOnce.Do(func() {
		file_complexpb_complex_proto_rawDescData = protoimpl.X.CompressGZIP(file_complexpb_complex_proto_rawDescData)
	})
	return file_complexpb_complex_proto_rawDescData
}

var file_complexpb_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_complexpb_complex_proto_goTypes = []interface{}{
	(*ComplexMessage)(nil), // 0: complex.ComplexMessage
	(*DummyMessage)(nil),   // 1: complex.DummyMessage
}
var file_complexpb_complex_proto_depIdxs = []int32{
	1, // 0: complex.ComplexMessage.dummy:type_name -> complex.DummyMessage
	1, // 1: complex.ComplexMessage.list:type_name -> complex.DummyMessage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_complexpb_complex_proto_init() }
func file_complexpb_complex_proto_init() {
	if File_complexpb_complex_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_complexpb_complex_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComplexMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_complexpb_complex_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DummyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_complexpb_complex_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_complexpb_complex_proto_goTypes,
		DependencyIndexes: file_complexpb_complex_proto_depIdxs,
		MessageInfos:      file_complexpb_complex_proto_msgTypes,
	}.Build()
	File_complexpb_complex_proto = out.File
	file_complexpb_complex_proto_rawDesc = nil
	file_complexpb_complex_proto_goTypes = nil
	file_complexpb_complex_proto_depIdxs = nil
}
